# Generated by Django 5.1.2 on 2026-01-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_name']},
        ),
    ]
