# Generated by Django 5.1.2 on 2025-12-09 07:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit (auto-filled from inventory retail_pricing)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
