# Generated by Django 6.0 on 2025-12-09 11:19

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorderitem_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_name', models.CharField(help_text='Name of the customer', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Customer address', null=True)),
                ('phone_numbers', models.CharField(blank=True, help_text='Phone numbers (can include multiple numbers separated by comma)', max_length=100, null=True)),
                ('pan_vat_number', models.CharField(blank=True, help_text='PAN/VAT number of the customer', max_length=50, null=True)),
                ('customer_type', models.CharField(choices=[('retail', 'Retail'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('distributor', 'Distributor'), ('workshop', 'Workshop')], help_text='Type of customer: Retail, Retailer, Wholesaler, Distributor, or Workshop', max_length=20)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bill',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['customer_type'], name='bill_custome_d8d6bc_idx'), models.Index(fields=['customer_name'], name='bill_custome_2684db_idx'), models.Index(fields=['is_active'], name='bill_is_acti_bce9ab_idx'), models.Index(fields=['created'], name='bill_created_59f5c5_idx')],
            },
        ),
    ]
