# Generated by Django 5.1.2 on 2025-12-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount_method',
            field=models.CharField(blank=True, choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default='amount', help_text='Discount method: Amount or Percentage', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='If Percentage, enter percent (0-100). If Amount, enter currency value.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], default='cash', help_text='Payment method used for the bill', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price before discount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid')], default='draft', help_text='Bill status: Draft, Pending, or Paid', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='bill_status_79d889_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['payment_method'], name='bill_payment_406554_idx'),
        ),
    ]
