# Generated by Django 6.0 on 2025-12-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('sales', '0004_bill_discount_method_bill_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch issuing this bill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch handling this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch fulfilling this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items', to='branch.branch'),
        ),
    ]
