# Generated by Django 5.1.2 on 2025-12-18 08:07

import apps.base.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('sales', '0005_bill_branch_salesorder_branch_salesorderitem_branch'),
        ('stock_management', '0004_inventory_branch_inventoryimage_branch_party_branch_and_more'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bill',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='salesorder',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this bill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this sales order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this sales order item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_items', to='tenant.tenant'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['tenant'], name='bill_tenant__b9779d_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['branch'], name='bill_branch__992b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant'], name='sales_order_tenant__7b1096_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['branch'], name='sales_order_branch__d924c4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['tenant'], name='sales_order_tenant__d574b3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['branch'], name='sales_order_branch__f81eea_idx'),
        ),
    ]
