# Generated by GitHub Copilot on 2025-12-21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_bill_managers_alter_salesorder_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='inventory_deducted',
            field=models.BooleanField(default=False, help_text='Whether inventory has been deducted for this item upon delivery'),
        ),
    ]
