# Generated by Django 5.1.2 on 2025-12-21 09:53

import apps.base.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('sales', '0007_add_inventory_deducted_field'),
        ('stock_management', '0005_alter_inventory_managers_and_more'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending'), ('on_hold', 'On Hold'), ('credit_sale', 'Credit Sale'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', help_text='Bill status: Draft, Pending, Paid, On Hold, Credit Sale, Cancelled, or Refunded', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('on_hold', 'On Hold'), ('credit_sale', 'Credit Sale'), ('partial', 'Partial'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(editable=False, help_text='Unique invoice number', max_length=50, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when invoice was created')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before tax and discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage (GST/VAT)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping/delivery charges', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('on_hold', 'On Hold'), ('credit_sale', 'Credit Sale'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], help_text='Payment method', max_length=20, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid so far', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField(blank=True, help_text='Invoice due date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Invoice notes or special instructions', null=True)),
                ('bill', models.OneToOneField(blank=True, help_text='Associated bill/invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='sales.bill')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch issuing this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.OneToOneField(blank=True, help_text='Associated sales order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.salesorder')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoice',
                'ordering': ['-invoice_date', '-created'],
            },
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('item_name', models.CharField(help_text='Item name (snapshot at time of invoice)', max_length=255)),
                ('part_number', models.CharField(blank=True, help_text='Part number (snapshot)', max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity on invoice', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage on this item', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for this line item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Notes for this item', null=True)),
                ('inventory', models.ForeignKey(help_text='Inventory item on invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='stock_management.inventory')),
                ('invoice', models.ForeignKey(help_text='Invoice this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this invoice item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'invoice_item',
                'ordering': ['invoice', 'created'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_invoice_5b7137_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='invoice_custome_120263_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_status'], name='invoice_payment_327947_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_invoice_3de1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-invoice_date'], name='invoice_invoice_af3231_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant'], name='invoice_tenant__ca8b25_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch'], name='invoice_branch__d23128_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sales_order'], name='invoice_sales_o_1f0b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['bill'], name='invoice_bill_id_8f85c6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='invoice_ite_invoice_74f52f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['inventory'], name='invoice_ite_invento_b076ba_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['tenant'], name='invoice_ite_tenant__e1da67_idx'),
        ),
    ]
