# Generated by Django 6.0 on 2025-12-21 10:51

import apps.base.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('sales', '0008_alter_bill_status_alter_salesorder_payment_status_and_more'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial'), ('on_hold', 'On Hold'), ('credit_sale', 'Credit Sale'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], help_text='Payment method', max_length=20, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid with this record', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField(blank=True, help_text='Due date inherited from invoice or order', null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this payment was recorded')),
                ('reference', models.CharField(blank=True, help_text='External payment reference or note', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes', null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch receiving the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='branch.branch')),
                ('customer', models.ForeignKey(help_text='Customer making the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice this payment is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice')),
                ('sales_order', models.ForeignKey(blank=True, help_text='Sales order this payment is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesorder')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this payment record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'ordering': ['-paid_at', '-created'],
                'indexes': [models.Index(fields=['tenant'], name='payment_tenant__bf1909_idx'), models.Index(fields=['invoice'], name='payment_invoice_6a55b6_idx'), models.Index(fields=['sales_order'], name='payment_sales_o_591e5c_idx'), models.Index(fields=['customer'], name='payment_custome_0e76f2_idx'), models.Index(fields=['payment_status'], name='payment_payment_285a08_idx'), models.Index(fields=['payment_method'], name='payment_payment_d8e241_idx'), models.Index(fields=['paid_at'], name='payment_paid_at_a3dd0c_idx')],
            },
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
    ]
