# Generated by Django 5.1.2 on 2025-12-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_payment_fields'),
    ]

    operations = []
