# Generated by Django 6.0 on 2025-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_invoice_invoice_payment_327947_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was received', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was received', null=True),
        ),
    ]
