# Generated by Django 5.1.2 on 2025-12-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_invoice_payment_date_salesorder_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], help_text='Latest payment method used', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial'), ('on_hold', 'On Hold'), ('credit_sale', 'Credit Sale'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Payment status (computed from payments)', max_length=20),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
