# Generated by Django 5.1.2 on 2025-12-22 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_salesorder_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=12)),
                ('bill', models.ForeignKey(help_text='Bill associated with this purchase item', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='sales.bill')),
            ],
        ),
    ]
