# Generated by Django 5.1.2 on 2025-12-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_update_purchaseitem_inventory_link'),
        ('stock_management', '0005_alter_inventory_managers_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseitem',
            new_name='purchase_it_bill_id_6f073e_idx',
            old_name='purchase_item_bill_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseitem',
            new_name='purchase_it_invento_7b4210_idx',
            old_name='purchase_item_inventory_idx',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='inventory',
            field=models.ForeignKey(help_text='Inventory item being purchased', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='stock_management.inventory'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product at the time of purchase', max_digits=12),
        ),
    ]
