# Generated by Django 5.1.2 on 2025-12-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_rename_purchase_item_bill_idx_purchase_it_bill_id_6f073e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the product at the time of purchase (auto-populated from inventory)', max_digits=12, null=True),
        ),
    ]
