# Generated by Django 5.1.2 on 2025-12-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_purchaseitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed Order'), ('ready_to_pack', 'Ready to Pack'), ('packed', 'Packed'), ('ready_to_depart', 'Ready to Depart'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='confirmed', help_text='Current status of the order', max_length=20),
        ),
    ]
