# Generated by Django 5.1.2 on 2026-01-20 07:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_bill_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Tax percentage (GST/VAT)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Tax percentage (GST/VAT)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
