# Generated by Django 5.1.2 on 2026-01-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_options'),
        ('sales', '0021_alter_delivery_fields'),
        ('tenant', '0007_alter_tenant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_bill_id_8f85c6_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='Related invoice (auto-created from paid invoice for online orders)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Related sales order (for online orders)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='sales.salesorder'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['invoice'], name='bill_invoice_cb3af5_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['sales_order'], name='bill_sales_o_7aac7f_idx'),
        ),
    ]
