# Generated by Django 5.1.2 on 2026-01-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_remove_invoice_invoice_bill_id_8f85c6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('on_hold', 'On Hold'), ('credit_sale', 'Credit Sale'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Payment status (computed from payments)', max_length=20),
        ),
    ]
