# Generated by Django 5.1.2 on 2026-01-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, help_text='Sales order item this invoice item originated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='sales.salesorderitem'),
        ),
    ]
