# Generated by Django 5.1.2 on 2026-02-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_add_district_rename_state_to_province'),
        ('sales', '0024_invoiceitem_sales_order_item'),
        ('tenant', '0007_alter_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches involved in this bill (derived from purchase items)', related_name='bills_involved', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Tenants involved in this bill (derived from purchase items)', related_name='bills_involved', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches involved in this invoice (derived from invoice items)', related_name='invoices_involved', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Tenants involved in this invoice (derived from invoice items)', related_name='invoices_involved', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches involved in this sales order (derived from line items)', related_name='sales_orders_involved', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Tenants involved in this sales order (derived from line items)', related_name='sales_orders_involved', to='tenant.tenant'),
        ),
    ]
