# Generated by Django 5.1.2 on 2026-02-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_add_district_rename_state_to_province'),
        ('sales', '0025_bill_branches_bill_tenants_invoice_branches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch issuing this bill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch issuing this invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch handling this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch fulfilling this item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_items', to='branch.branch'),
        ),
    ]
