# Generated by Django 6.0 on 2026-01-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
