# Generated by Django 5.1.2 on 2026-01-19 07:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscriberemail'),
        ('tenant', '0003_tenant_location_tenant_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='district',
            field=models.CharField(blank=True, help_text='District/County where business is located', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, message='District name must be at least 2 characters long')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='province',
            field=models.CharField(blank=True, help_text='Province/State where business is located', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Province name must be at least 2 characters long')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='business_name',
            field=models.CharField(help_text='Name of the business/tenant', max_length=255, validators=[django.core.validators.MinLengthValidator(2, message='Business name must be at least 2 characters long')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(help_text='Business email address (must be unique)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='location',
            field=models.CharField(blank=True, help_text='Business location/address', max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3, message='Location must be at least 3 characters long')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Subscription plan for this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN/Tax registration number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='PAN number must be 9-15 alphanumeric characters (uppercase)', regex='^[A-Z0-9]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in a valid format. E.g., '+977-9841234567' or '9841234567'", regex='^\\+?[0-9]{1,4}?[-.\\s]?\\(?[0-9]{1,3}?\\)?[-.\\s]?[0-9]{1,4}[-.\\s]?[0-9]{1,4}[-.\\s]?[0-9]{1,9}$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='trial', help_text='Current status of the tenant', max_length=20),
        ),
    ]
