# Generated by Django 5.1.2 on 2026-01-19 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_tenant_district_tenant_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN/Tax registration number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='PAN number must be exactly 9 digits (numeric only)', regex='^[0-9]{9}$')]),
        ),
    ]
