# Generated by Django 5.1.2 on 2026-01-19 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_alter_tenant_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='district',
            field=models.CharField(blank=True, help_text='District/County where business is located', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, message='District name must be at least 2 characters long'), django.core.validators.RegexValidator(message='District name can only contain letters, spaces, and hyphens', regex='^[a-zA-Z\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='province',
            field=models.CharField(blank=True, help_text='Province/State where business is located', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Province name must be at least 2 characters long'), django.core.validators.RegexValidator(message='Province name can only contain letters, spaces, and hyphens', regex='^[a-zA-Z\\s-]+$')]),
        ),
    ]
