# Generated by Django 6.0.1 on 2026-01-19 08:20

import apps.tenant.models.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_alter_tenant_district_alter_tenant_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number (mobile: 10 digits starting with 97/98, landline: 6-8 digits, supports +977 format)', max_length=20, null=True, validators=[apps.tenant.models.tenant.validate_phone_number]),
        ),
    ]
