# Generated by Django 6.0 on 2025-12-08 08:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('party_type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], help_text='Type of party: Supplier or Customer', max_length=20)),
                ('customer_type', models.CharField(blank=True, choices=[('retail_customer', 'Retail Customer'), ('retailer', 'Retailer'), ('workshop', 'Workshop'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler')], help_text='Type of customer (only applicable for customers)', max_length=20, null=True)),
                ('party_name', models.CharField(help_text='Name of the party/business', max_length=255)),
                ('contact_person', models.CharField(blank=True, help_text='Name of the contact person', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Street address', null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, help_text='State or Province', max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, help_text='PAN (Permanent Account Number)', max_length=20, null=True)),
                ('payment_terms', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('7_day_credit', '7 Day Credit'), ('15_day_credit', '15 Day Credit'), ('30_day_credit', '30 Day Credit'), ('45_day_credit', '45 Day Credit')], default='cash', help_text='Payment terms for transactions', max_length=20)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'party',
                'ordering': ['party_name'],
                'indexes': [models.Index(fields=['party_type'], name='party_party_t_7ec0ba_idx'), models.Index(fields=['customer_type'], name='party_custome_6e70f4_idx'), models.Index(fields=['party_name'], name='party_party_n_b0f8d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('po_number', models.CharField(help_text='Purchase Order Number', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('received', 'Received'), ('billed', 'Billed')], default='draft', help_text='Status of the purchase order', max_length=20)),
                ('order_date', models.DateField(help_text='Date when the order was placed')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('purchase_invoice', models.FileField(blank=True, help_text='Upload purchase invoice document', null=True, upload_to='purchase_invoices/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('terms_and_condition', models.TextField(blank=True, help_text='Terms and conditions', null=True)),
                ('supplier', models.ForeignKey(help_text='Supplier for this purchase order', limit_choices_to={'party_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='stock_management.party')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchase_order',
                'ordering': ['-order_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('item_name', models.CharField(help_text='Name of the item', max_length=255)),
                ('part_number', models.CharField(blank=True, help_text='Part number or SKU', max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity ordered', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage (e.g., 18.00 for 18%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_description', models.CharField(blank=True, help_text='Description of discount applied', max_length=255, null=True)),
                ('purchase_order', models.ForeignKey(help_text='Purchase order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_management.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'db_table': 'purchase_order_item',
                'ordering': ['purchase_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='purchase_or_po_numb_1d7f45_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_86ae3f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchase_or_order_d_37b60a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='purchase_or_supplie_6b4199_idx'),
        ),
    ]
