# Generated by Django 6.0 on 2025-12-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Credit limit for the party', max_digits=12),
        ),
        migrations.AddField(
            model_name='party',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance for the party', max_digits=12),
        ),
    ]
