# Generated by Django 6.0 on 2025-12-08 10:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_party_credit_limit_party_opening_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('item_name', models.CharField(help_text='Name of the inventory item', max_length=255)),
                ('category', models.CharField(choices=[('local', 'Local'), ('original', 'Original')], help_text='Category of the item', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler')], help_text='Type of vehicle this part is for', max_length=20)),
                ('part_number', models.CharField(blank=True, help_text='Part number or SKU', max_length=100, null=True)),
                ('hsn_code', models.CharField(blank=True, help_text='HSN (Harmonized System of Nomenclature) Code', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum stock level before reordering', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('storage_location', models.CharField(blank=True, help_text='Storage location or warehouse location', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum Retail Price (MRP)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('retail_pricing', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retail price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wholesale price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('distributor_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Distributor price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('warranty_period', models.CharField(choices=[('no_warranty', 'No Warranty'), ('1_month', '1 Month'), ('2_month', '2 Month'), ('3_month', '3 Month'), ('4_month', '4 Month'), ('5_month', '5 Month'), ('6_month', '6 Month'), ('9_month', '9 Month'), ('12_month', '12 Month'), ('24_month', '24 Month')], default='no_warranty', help_text='Warranty period for the item', max_length=20)),
                ('barcode', models.CharField(blank=True, help_text='Barcode for scanning', max_length=100, null=True, unique=True)),
                ('vehicle_bike_details', models.TextField(blank=True, help_text='Vehicle/Bike details', null=True)),
                ('model', models.CharField(blank=True, help_text='Model name', max_length=255, null=True)),
                ('type', models.CharField(blank=True, help_text='Type of vehicle/part', max_length=255, null=True)),
                ('party', models.ForeignKey(blank=True, help_text='Party/Supplier associated with this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='stock_management.party')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(help_text='Part image', upload_to='inventory_images/')),
                ('description', models.CharField(blank=True, help_text='Optional description for the image', max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary image')),
                ('inventory', models.ForeignKey(help_text='Inventory item this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stock_management.inventory')),
            ],
            options={
                'verbose_name': 'Inventory Image',
                'verbose_name_plural': 'Inventory Images',
                'db_table': 'inventory_image',
                'ordering': ['-is_primary', 'created'],
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['item_name'], name='inventory_item_na_084c23_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['category'], name='inventory_categor_ee7c14_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['vehicle_type'], name='inventory_vehicle_44c3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['part_number'], name='inventory_part_nu_69121a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['barcode'], name='inventory_barcode_04d106_idx'),
        ),
    ]
