# Generated by Django 6.0 on 2025-12-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('stock_management', '0003_inventory_inventoryimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch that owns this inventory record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='inventoryimage',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch associated with this image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_images', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='party',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch that manages this party', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch placing this purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch responsible for this purchase item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='branch.branch'),
        ),
    ]
