# Generated by Django 5.1.2 on 2025-12-18 08:07

import apps.base.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('stock_management', '0004_inventory_branch_inventoryimage_branch_party_branch_and_more'),
        ('tenant', '0002_alter_tenant_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inventory',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='inventoryimage',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='party',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='purchaseorder',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='purchaseorderitem',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this inventory item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryimage',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this inventory image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_images', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='party',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this purchase order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this purchase order item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='tenant.tenant'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['tenant'], name='inventory_tenant__997b11_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['branch'], name='inventory_branch__f2ebe8_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tenant'], name='party_tenant__793243_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['branch'], name='party_branch__fda00c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant'], name='purchase_or_tenant__98a69c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['branch'], name='purchase_or_branch__2ca086_idx'),
        ),
    ]
