# Generated by Django 6.0 on 2025-12-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0005_alter_inventory_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('received', 'Received'), ('billed', 'Billed'), ('returned', 'Returned')], default='draft', help_text='Status of the purchase order', max_length=20),
        ),
    ]
