# Generated by Django 6.0 on 2026-01-05 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_options'),
        ('stock_management', '0006_alter_purchaseorder_status'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this party', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['created_by'], name='party_created_f86c8d_idx'),
        ),
    ]
