# Generated by Django 5.1.2 on 2026-01-19 09:11

import apps.stock_management.models.parties
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0007_party_created_by_party_party_created_f86c8d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True, validators=[apps.stock_management.models.parties.validate_phone_number]),
        ),
    ]
