# Generated by Django 5.1.2 on 2026-01-20 12:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0008_alter_party_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='discount_description',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Tax percentage (e.g., 18.00 for 18%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
