# Generated by Django 6.0 on 2026-01-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_management", "0009_alter_inventory_barcode"),
        (
            "stock_management",
            "0009_remove_purchaseorderitem_discount_description_and_more",
        ),
    ]

    operations = []
