# Generated by Django 5.1.2 on 2026-01-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0009_alter_inventory_barcode'),
        ('stock_management', '0009_remove_purchaseorderitem_discount_description_and_more'),
    ]

    operations = [
    ]
