# Generated by Django 6.0 on 2026-01-21 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_management", "0010_merge_20260121_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="invoice_pdf",
            field=models.FileField(
                blank=True,
                help_text="Upload supplier invoice in PDF format",
                null=True,
                upload_to="purchase_invoices/pdfs/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
