# Generated by Django 5.2.7 on 2026-01-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_management", "0011_purchaseorder_invoice_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Primary image for inventory item (shown in inventory list)",
                null=True,
                upload_to="inventory_images/",
            ),
        ),
    ]
