# Generated by Django 5.2.7 on 2026-01-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_management", "0012_add_primary_image_to_inventory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryimage",
            options={
                "ordering": ["created"],
                "verbose_name": "Inventory Image",
                "verbose_name_plural": "Inventory Images",
            },
        ),
        migrations.RemoveField(
            model_name="inventoryimage",
            name="is_primary",
        ),
    ]
