# Generated by Django 5.2.7 on 2026-01-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_management", "0010_merge_20260121_1621"),
        ("stock_management", "0013_alter_inventoryimage_options_and_more"),
    ]

    operations = []
