# Generated by Django 5.1.2 on 2026-02-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_add_district_rename_state_to_province'),
        ('stock_management', '0014_merge_20260123_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch that owns this inventory record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='party',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch that manages this party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch placing this purchase order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='branch.branch'),
        ),
    ]
