# Generated by Django 5.1.2 on 2026-02-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_add_district_rename_state_to_province'),
        ('stock_management', '0015_alter_inventory_branch_alter_party_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryimage',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch associated with this image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_images', to='branch.branch'),
        ),
    ]
