# Generated by Django 5.1.2 on 2025-12-14 07:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_management', '0003_inventory_inventoryimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(help_text='User who owns this cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity of this item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at the time of adding to cart', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cart', models.ForeignKey(help_text='Cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('inventory', models.ForeignKey(help_text='Inventory item', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stock_management.inventory')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['cart', 'inventory'], name='cart_items_cart_id_d74080_idx'), models.Index(fields=['created'], name='cart_items_created_4fada8_idx')],
                'unique_together': {('cart', 'inventory')},
            },
        ),
    ]
