# Generated by Django 5.1.2 on 2025-12-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_removed',
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this cart is active'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this cart item is active'),
        ),
    ]
