# Generated by Django 5.1.2 on 2025-12-18 07:02

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_favorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favorite',
            new_name='favorites_user_id_ec9c13_idx',
            old_name='favorites_user_invento_idx',
        ),
        migrations.RenameIndex(
            model_name='favorite',
            new_name='favorites_user_id_65f342_idx',
            old_name='favorites_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='favorite',
            new_name='favorites_is_acti_598c2b_idx',
            old_name='favorites_is_active_idx',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
