"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment; fallback to existing value for local dev
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-a*iz)9%+@ja6bpla^c!ll#+3f39d1)bu-sl*e3^&e%p7_u+ste'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Controlled via environment. Example in env.example: DEBUG=True
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'backend.servespare.xyz',
    'www.backend.servespare.xyz',
    'www.imspravidhi.vercel.app',
    'servespare.xyz',
    'localhost',
    '127.0.0.1',
    'unopinionated-kiddingly-verline.ngrok-free.dev',
    'imspravidhi.vercel.app',
]

# Allow localhost and ngrok host for CSRF and CORS (used by corsheaders middleware)
# Include the scheme (https/http) as required by Django for CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'https://unopinionated-kiddingly-verline.ngrok-free.dev',
    'https://imspravidhi.vercel.app',
    'https://backend.servespare.xyz',
    'https://servespare.xyz',
]

# If you need cross-origin requests from frontend, explicitly allow it via django-cors-headers settings.
# Consolidated to avoid duplicate assignments.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'https://unopinionated-kiddingly-verline.ngrok-free.dev',
    'https://imspravidhi.vercel.app',
    'https://backend.servespare.xyz',
    'https://servespare.xyz',
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]

# If you'd rather allow any origin during development, you can set
# CORS_ALLOW_ALL_ORIGINS = True


# Application definition
from core.configuration.apps import PRELOAD_APPS, THIRD_PARTY_APPS, LOCAL_APPS
from core.configuration.rest import REST_FRAMEWORK, SPECTACULAR_SETTINGS
from core.configuration.auth import SIMPLE_JWT, AUTHENTICATION_BACKENDS, SITE_ID

INSTALLED_APPS = PRELOAD_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.base.middleware.TenantMiddleware',
    'apps.base.middleware.AuditMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#     'ENGINE': 'django.db.backends.mysql',
#     'NAME': 'servesp1_servespare',
#     'HOST': 'localhost',
#     'PORT': '3306',
#     'USER': 'servesp1_admin',
#     'PASSWORD' :'github.com'

# }
    
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'users.User'
# Site ID for django.contrib.sites (required by django-allauth)

# Email configuration
# If SMTP creds are missing while DEBUG is True, fall back to console backend so emails are visible during development.
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@serveiq.com')

if DEBUG and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
