# Generated by Django 5.1.2 on 2026-01-18 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('tenant', '0003_tenant_location_tenant_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that this audit log belongs to. Deleted when tenant is deleted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenant.tenant'),
        ),
    ]
