# Generated by Django 6.0.1 on 2026-01-19 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_auditlog_tenant'),
        ('tenant', '0007_alter_tenant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenant.tenant'),
        ),
    ]
