# Generated by Django 6.0 on 2025-12-08 06:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address for the user.', max_length=254, null=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager')], db_index=True, default='cashier', help_text='User role determining access level and permissions.', max_length=30, verbose_name='role')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Contact phone number.', max_length=20, null=True, verbose_name='phone number')),
                ('full_name', models.CharField(blank=True, help_text='Full name of the user.', max_length=255, null=True, verbose_name='full name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Current status of the user account.', max_length=20, verbose_name='status')),
                ('must_change_password', models.BooleanField(default=False, help_text='Indicates if the user must change their password on next login.', verbose_name='must change password')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful login.', null=True, verbose_name='last login at')),
                ('avatar', models.ImageField(blank=True, help_text='Profile avatar image.', null=True, upload_to='avatars/', verbose_name='avatar')),
                ('workspace_id', models.CharField(blank=True, db_index=True, help_text='Workspace identifier for multi-tenancy.', max_length=100, null=True, verbose_name='workspace ID')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', help_text='Tenant organization this user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenant.tenant', verbose_name='tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['email'], name='users_email_idx'), models.Index(fields=['status', 'is_active'], name='users_status_active_idx'), models.Index(fields=['workspace_id', 'status'], name='users_workspace_status_idx'), models.Index(fields=['created'], name='users_created_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
