# Generated by Django 6.0 on 2025-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Indicates if the user must change their password on next login.', verbose_name='must change password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sub_admin', 'Sub_Admin'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager')], db_index=True, default='cashier', help_text='User role determining access level and permissions.', max_length=30, verbose_name='role'),
        ),
    ]
