# Generated by Django 5.1.2 on 2025-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sub_admin', 'Sub_Admin'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager'), ('customer', 'Customer')], db_index=True, default='cashier', help_text='User role determining access level and permissions.', max_length=30, verbose_name='role'),
        ),
    ]
