# Generated by Django 5.1.2 on 2025-12-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sub_admin', 'Sub_Admin'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager'), ('customer', 'Customer')], db_index=True, default='customer', help_text='User role determining access level and permissions.', max_length=30, verbose_name='role'),
        ),
    ]
