# Generated by Django 5.1.2 on 2025-12-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='User location or address.', max_length=255, null=True, verbose_name='location'),
        ),
    ]
