# Generated by Django 6.0 on 2025-12-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('users', '0004_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='branch.branch'),
        ),
    ]
