# Generated by Django 6.0 on 2025-12-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_branch'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
