# Generated by Django 5.1.2 on 2025-12-18 07:02

import apps.base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
    ]
