# Generated by Django 5.1.2 on 2026-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address for the user.', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Contact phone number.', max_length=20, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
