# Generated by Django 5.1.2 on 2026-01-19 08:25

import apps.users.models.user_model
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile avatar image. Max size: 5MB. Allowed formats: JPG, PNG, GIF, WEBP. Min: 50x50px, Max: 2000x2000px.', null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message='Only JPG, JPEG, PNG, GIF, and WEBP images are allowed.'), apps.users.models.user_model.validate_avatar_size, apps.users.models.user_model.validate_avatar_dimensions], verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address for the user.', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the user.', max_length=255, null=True, validators=[apps.users.models.user_model.validate_full_name], verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='User location or address.', max_length=255, null=True, validators=[apps.users.models.user_model.validate_location], verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Contact phone number.', max_length=20, null=True, unique=True, validators=[apps.users.models.user_model.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with this username already exists.'}, help_text='Required. 3-150 characters. Letters, digits, hyphens, underscores, and periods only.', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Username must be at least 3 characters long.'), apps.users.models.user_model.validate_username_chars], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workspace_id',
            field=models.CharField(blank=True, db_index=True, help_text='Workspace identifier for multi-tenancy.', max_length=100, null=True, validators=[apps.users.models.user_model.validate_workspace_id], verbose_name='workspace ID'),
        ),
    ]
