# Generated by Django 5.1.2 on 2026-01-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Indicates if two-factor authentication is enabled for this user account.', verbose_name='two factor authentication enabled'),
        ),
    ]
