# Generated by Django 5.1.2 on 2026-02-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_add_district_rename_state_to_province'),
        ('users', '0009_user_two_factor_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='branch.branch'),
        ),
    ]
