# Generated by Django 5.1.2 on 2026-01-06 06:49

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the person sending the message', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the person', max_length=254)),
                ('phone_number', models.CharField(help_text='Phone number of the person', max_length=20)),
                ('company', models.CharField(help_text='Company name', max_length=255)),
                ('message', models.TextField(help_text='The message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read by support')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['email'], name='message_mes_email_eeb596_idx'), models.Index(fields=['is_read'], name='message_mes_is_read_4f7689_idx'), models.Index(fields=['-created'], name='message_mes_created_e0cf2c_idx')],
            },
        ),
    ]
