# Generated by Django 6.0 on 2025-12-09 09:26

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('esewa', 'eSewa'), ('fonepay', 'FonePay'), ('cash', 'Cash')], help_text='Type of account: Bank Account, eSewa, FonePay, or Cash', max_length=20)),
                ('account_name', models.CharField(help_text='Name of the account', max_length=255)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank (required for bank accounts)', max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Account number or identifier', max_length=100, null=True)),
                ('account_holders_name', models.CharField(blank=True, help_text='Name of the account holder', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_account',
                'ordering': ['account_name'],
                'indexes': [models.Index(fields=['account_type'], name='bank_accoun_account_8e96b6_idx'), models.Index(fields=['account_name'], name='bank_accoun_account_77e282_idx'), models.Index(fields=['is_active'], name='bank_accoun_is_acti_fb51b2_idx')],
            },
        ),
    ]
