# Generated by Django 5.1.2 on 2025-12-16 10:39

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0002_alter_bankaccount_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('transfer', 'Transfer')], help_text='Type of transaction: cash_in, cash_out, transfer', max_length=20)),
                ('source_description', models.TextField(blank=True, help_text='Source or description of the transaction', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Absolute amount of the transaction', max_digits=12)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the transaction')),
                ('from_account', models.ForeignKey(blank=True, help_text='Source account for transfer (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions_from', to='cashandbank.bankaccount')),
                ('to_account', models.ForeignKey(blank=True, help_text='Destination account for transfer (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions_to', to='cashandbank.bankaccount')),
            ],
            options={
                'verbose_name': 'Cash Transaction',
                'verbose_name_plural': 'Cash Transactions',
                'db_table': 'cash_transaction',
                'ordering': ['-transaction_date', '-created'],
                'indexes': [models.Index(fields=['transaction_type'], name='cash_transa_transac_b4ba0d_idx'), models.Index(fields=['transaction_date'], name='cash_transa_transac_1d744f_idx'), models.Index(fields=['is_active'], name='cash_transa_is_acti_39a984_idx')],
            },
        ),
    ]
