# Generated by Django 6.0 on 2025-12-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0002_alter_bankaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
