# Generated by Django 6.0 on 2025-12-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0003_alter_bankaccount_id'),
        ('cashandbank', '0003_cashtransaction'),
    ]

    operations = [
    ]
