# Generated by Django 6.0 on 2025-12-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0004_merge_0003_alter_bankaccount_id_0003_cashtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
