# Generated by Django 6.0 on 2025-12-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('cashandbank', '0005_alter_cashtransaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch associated with this bank account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch associated with this cash transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='branch.branch'),
        ),
    ]
