# Generated by Django 5.1.2 on 2025-12-18 08:07

import apps.base.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('cashandbank', '0006_bankaccount_branch_cashtransaction_branch'),
        ('tenant', '0002_alter_tenant_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bankaccount',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cashtransaction',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this bank account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this cash transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='tenant.tenant'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['tenant'], name='bank_accoun_tenant__03ee51_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['branch'], name='bank_accoun_branch__bf21d0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['tenant'], name='cash_transa_tenant__62ecd4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['branch'], name='cash_transa_branch__0981b4_idx'),
        ),
    ]
