# Generated by Django 6.0 on 2025-12-23 08:42

import apps.base.managers
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('cashandbank', '0007_alter_bankaccount_managers_and_more'),
        ('tenant', '0002_alter_tenant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current cash balance for the tenant+branch', max_digits=14)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch for this cash balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balances', to='branch.branch')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this balance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_balances', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Cash Balance',
                'verbose_name_plural': 'Cash Balances',
                'db_table': 'cash_balance',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['tenant'], name='cash_balanc_tenant__bada0f_idx'), models.Index(fields=['branch'], name='cash_balanc_branch__4df151_idx')],
            },
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], help_text='cash_in or cash_out', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this manual entry', max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch associated with this manual entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_entries', to='branch.branch')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this manual entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Manual Entry',
                'verbose_name_plural': 'Manual Entries',
                'db_table': 'manual_entry',
                'ordering': ['-entry_date'],
                'indexes': [models.Index(fields=['tenant'], name='manual_entr_tenant__94930d_idx'), models.Index(fields=['branch'], name='manual_entr_branch__0ee4ea_idx'), models.Index(fields=['transaction_type'], name='manual_entr_transac_7139e9_idx')],
            },
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
    ]
