# Generated by Django 6.0 on 2025-12-23 11:41

import apps.base.managers
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('cashandbank', '0008_cashbalance_manualentry'),
        ('tenant', '0002_alter_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance for this bank account', max_digits=14),
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount transferred', max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(help_text='Destination bank account for this transfer', on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers', to='cashandbank.bankaccount')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch from which cash is deducted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers', to='branch.branch')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this transfer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'verbose_name_plural': 'Bank Transfers',
                'db_table': 'bank_transfer',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['tenant'], name='bank_transf_tenant__bc3b8c_idx'), models.Index(fields=['branch'], name='bank_transf_branch__d0d15c_idx'), models.Index(fields=['bank_account'], name='bank_transf_bank_ac_41e3a3_idx')],
            },
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
    ]
