# Generated by Django 6.0 on 2025-12-24 06:11

import apps.base.managers
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('cashandbank', '0009_bankaccount_balance_banktransfer'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('flagged', 'Flagged')], default='open', help_text='Status of the shift: open, closed, or flagged', max_length=20)),
                ('opening_float', models.DecimalField(decimal_places=2, help_text='Cash amount at start of shift', max_digits=14)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when shift was opened')),
                ('expected_amount', models.DecimalField(decimal_places=2, help_text='Expected cash amount (opening + sales - adjustments)', max_digits=14)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual counted cash amount at close', max_digits=14, null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when shift was closed', null=True)),
                ('variance_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between expected and actual (can be negative)', max_digits=14, null=True)),
                ('variance_reason', models.TextField(blank=True, help_text='Reason for variance if closing amount differs from expected', null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes about the shift', null=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Auto-flagged if variance exceeds threshold (e.g., >100)')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch where this shift occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_shifts', to='branch.branch')),
                ('cashier', models.ForeignKey(help_text='Cashier conducting this shift', on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this shift', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_shifts', to='tenant.tenant')),
                ('cash_balance', models.ForeignKey(blank=True, help_text='Linked cash balance for this shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_shifts', to='cashandbank.cashbalance')),
            ],
            options={
                'verbose_name': 'Cashier Shift',
                'verbose_name_plural': 'Cashier Shifts',
                'db_table': 'cashier_shift',
                'ordering': ['-opened_at'],
            },
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('opening', 'Opening'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('sale', 'Sale'), ('closing', 'Closing')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount involved in transaction', max_digits=14)),
                ('description', models.TextField(blank=True, help_text='Description or reason for transaction', null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (e.g., bill, invoice)', max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='ID of referenced object', max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this transaction occurred')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transactions', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(help_text='Shift this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shift_transactions', to='cashandbank.cashiershift')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_transactions', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Shift Transaction',
                'verbose_name_plural': 'Shift Transactions',
                'db_table': 'shift_transaction',
                'ordering': ['transaction_date'],
            },
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['tenant'], name='cashier_shi_tenant__699a20_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['branch'], name='cashier_shi_branch__c61cce_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['cashier'], name='cashier_shi_cashier_3ccce6_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['status'], name='cashier_shi_status_d42e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['opened_at'], name='cashier_shi_opened__f243f8_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['is_flagged'], name='cashier_shi_is_flag_4b5571_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttransaction',
            index=models.Index(fields=['shift'], name='shift_trans_shift_i_56b1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttransaction',
            index=models.Index(fields=['tenant'], name='shift_trans_tenant__d378f1_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttransaction',
            index=models.Index(fields=['transaction_type'], name='shift_trans_transac_31aec3_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttransaction',
            index=models.Index(fields=['transaction_date'], name='shift_trans_transac_cfc09e_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='shift_trans_referen_94a6a2_idx'),
        ),
    ]
