# Generated by Django 6.0 on 2025-12-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('cashandbank', '0010_cashiershift_shifttransaction_and_more'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='transferred_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when shift was transferred', null=True),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='transferred_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_transferred_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='transferred_to',
            field=models.CharField(blank=True, help_text='Name of the person/cashier this shift was transferred to', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['transferred_to'], name='cashier_shi_transfe_e3f336_idx'),
        ),
    ]
