# Generated by Django 5.1.2 on 2025-12-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0011_cashiershift_transferred_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiershift',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('flagged', 'Flagged'), ('transferred', 'Transferred')], default='open', help_text='Status of the shift: open, closed, or flagged', max_length=20),
        ),
    ]
