# Generated by Django 5.1.2 on 2025-12-24 06:42

import apps.cashandbank.models.cash_in_hand
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0012_alter_cashiershift_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cashtransaction',
            managers=[
                ('objects', apps.cashandbank.models.cash_in_hand.CashTransactionManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='cashiershift',
            name='cash_balance',
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected cash amount (opening + sales - adjustments)', max_digits=14, null=True),
        ),
    ]
