# Generated by Django 5.1.2 on 2025-12-24 07:16

import apps.base.managers
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('cashandbank', '0013_alter_cashtransaction_managers_and_more'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ledger_type', models.CharField(choices=[('general', 'General Ledger'), ('sales', 'Sales Ledger'), ('purchase', 'Purchase Ledger'), ('account', 'Account Ledger')], default='general', help_text='Type of ledger (general, sales, purchase, account)', max_length=20)),
                ('transaction_type', models.CharField(choices=[('opening', 'Shift Opening'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('sale', 'Sale'), ('closing', 'Shift Closing'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], help_text='Type of transaction', max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (inflow/cash in)', max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (outflow/cash out)', max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running balance after this transaction', max_digits=14)),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('reference', models.CharField(blank=True, help_text='Reference number (e.g., Shift #shift_17, Bill #123)', max_length=100, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (shift, bill, invoice, etc.)', max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='ID of referenced object', max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of transaction')),
                ('is_manual_entry', models.BooleanField(default=False, help_text='Whether this was a manual entry')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this ledger belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_ledgers', to='branch.branch')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, help_text='Shift this ledger entry belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_ledgers', to='cashandbank.cashiershift')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this ledger', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_ledgers', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Account Ledger',
                'verbose_name_plural': 'Account Ledgers',
                'db_table': 'account_ledger',
                'ordering': ['transaction_date', 'id'],
                'indexes': [models.Index(fields=['shift'], name='account_led_shift_i_0fd646_idx'), models.Index(fields=['tenant'], name='account_led_tenant__29476d_idx'), models.Index(fields=['ledger_type'], name='account_led_ledger__69f76c_idx'), models.Index(fields=['transaction_type'], name='account_led_transac_75a177_idx'), models.Index(fields=['transaction_date'], name='account_led_transac_556d0d_idx'), models.Index(fields=['branch'], name='account_led_branch__bb0291_idx'), models.Index(fields=['tenant', 'shift', 'transaction_date'], name='account_led_tenant__bef0f7_idx')],
            },
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
    ]
