# Generated by Django 5.1.2 on 2025-12-24 07:35

import apps.base.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_managers'),
        ('cashandbank', '0014_add_account_ledger'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLedger',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Ledger',
                'verbose_name_plural': 'Purchase Ledgers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cashandbank.accountledger',),
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='SalesLedger',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Ledger',
                'verbose_name_plural': 'Sales Ledgers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cashandbank.accountledger',),
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='accountledger',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_shift_i_0fd646_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_tenant__29476d_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_transac_75a177_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_branch__bb0291_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_tenant__bef0f7_idx',
        ),
        migrations.RenameIndex(
            model_name='accountledger',
            new_name='cashandbank_transac_100546_idx',
            old_name='account_led_transac_556d0d_idx',
        ),
        migrations.RenameIndex(
            model_name='accountledger',
            new_name='cashandbank_ledger__418be1_idx',
            old_name='account_led_ledger__69f76c_idx',
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='transaction_type',
            field=models.CharField(choices=[('opening', 'Shift Opening'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('sale', 'Sale'), ('purchase', 'Purchase'), ('closing', 'Shift Closing'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], help_text='Type of transaction', max_length=20),
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['shift', 'ledger_type'], name='cashandbank_shift_i_f25c03_idx'),
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['tenant', 'branch'], name='cashandbank_tenant__5f790f_idx'),
        ),
        migrations.AlterModelTable(
            name='accountledger',
            table=None,
        ),
    ]
