# Generated by Django 6.0 on 2025-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0015_add_purchase_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_type', models.CharField(choices=[('issued', 'Issued'), ('given', 'Given')], max_length=10)),
                ('cheque_number', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=32, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminder_setting', models.CharField(choices=[('7', '7 days before'), ('3', '3 days before'), ('1', '1 day before'), ('0', 'Same day')], default='7', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['-due_date', '-created'],
            },
        ),
    ]
