# Generated by Django 5.1.2 on 2026-01-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0015_add_purchase_transaction_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseLedger',
        ),
        migrations.DeleteModel(
            name='SalesLedger',
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='ledger_type',
            field=models.CharField(
                choices=[('general', 'General Ledger'), ('account', 'Account Ledger')],
                default='general',
                help_text='Type of ledger (general, account)',
                max_length=20,
            ),
        ),
    ]
