# Generated by Django 5.1.2 on 2026-01-04 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_options'),
        ('cashandbank', '0016_cheque'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountledger',
            options={'ordering': ['transaction_date', 'id'], 'verbose_name': 'Account Ledger', 'verbose_name_plural': 'Account Ledgers'},
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='cashandbank_shift_i_f25c03_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='cashandbank_tenant__5f790f_idx',
        ),
        migrations.RenameIndex(
            model_name='accountledger',
            new_name='account_led_ledger__69f76c_idx',
            old_name='cashandbank_ledger__418be1_idx',
        ),
        migrations.RenameIndex(
            model_name='accountledger',
            new_name='account_led_transac_556d0d_idx',
            old_name='cashandbank_transac_100546_idx',
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['shift'], name='account_led_shift_i_0fd646_idx'),
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['tenant'], name='account_led_tenant__29476d_idx'),
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['transaction_type'], name='account_led_transac_75a177_idx'),
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['branch'], name='account_led_branch__bb0291_idx'),
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['tenant', 'shift', 'transaction_date'], name='account_led_tenant__bef0f7_idx'),
        ),
        migrations.AlterModelTable(
            name='accountledger',
            table='account_ledger',
        ),
    ]
