# Generated by Django 5.1.2 on 2026-01-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0016_remove_sales_purchase_ledgers'),
        ('cashandbank', '0017_alter_accountledger_options_and_more'),
    ]

    operations = [
    ]
