# Generated by Django 5.1.2 on 2026-01-04 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_options'),
        ('cashandbank', '0018_merge_20260104_1734'),
        ('tenant', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_shift_i_0fd646_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_tenant__29476d_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_transac_75a177_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_branch__bb0291_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountledger',
            name='account_led_tenant__bef0f7_idx',
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='ledger_type',
            field=models.CharField(choices=[('general', 'General Ledger'), ('purchase', 'Purchase Ledger'), ('sale', 'Sale Ledger'), ('account', 'Account Ledger')], default='general', help_text='Type of ledger (general, purchase, account)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['shift', 'ledger_type'], name='account_led_shift_i_aa4b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountledger',
            index=models.Index(fields=['tenant', 'branch'], name='account_led_tenant__8f5c4b_idx'),
        ),
    ]
