# Generated by Django 5.1.2 on 2026-01-19 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0019_add_sale_ledger_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashiershift',
            new_name='cashier_shi_transfe_92a8f3_idx',
            old_name='cashier_shi_transfe_e3f336_idx',
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='transferred_to',
            field=models.ForeignKey(blank=True, help_text='Cashier who received this shift transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_transferred_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
