# Generated by Django 5.1.2 on 2026-01-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashandbank', '0020_rename_cashier_shi_transfe_e3f336_idx_cashier_shi_transfe_92a8f3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('sale', 'Sale')], help_text='Type of transaction', max_length=20),
        ),
    ]
