# Generated by Django 5.2.7 on 2026-01-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0003_alter_branch_options"),
        ("cashandbank", "0021_alter_shifttransaction_transaction_type"),
        ("tenant", "0007_alter_tenant_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="account_holders_name",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="account_holder_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the account holder (optional for bank accounts)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="wallet_id",
            field=models.CharField(
                blank=True,
                help_text="Wallet ID or phone number (required for eSewa/FonePay)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_name",
            field=models.CharField(
                help_text='Display name for the account (e.g., "Primary Bank", "Cash Register")',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(
                blank=True,
                help_text="Bank account number (required for bank accounts)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("bank", "Bank Account"),
                    ("esewa", "eSewa"),
                    ("fonepay", "FonePay"),
                    ("cash", "Cash"),
                ],
                help_text="Type of account: bank, esewa, fonepay, or cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Current balance for this account",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch associated with this account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_accounts",
                to="branch.branch",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this account",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="tenant.tenant",
            ),
        ),
    ]
