# Generated by Django 5.1.2 on 2026-02-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_add_district_rename_state_to_province'),
        ('cashandbank', '0022_remove_bankaccount_account_holders_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountledger',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this ledger belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_ledgers', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch associated with this account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch from which cash is deducted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='cashbalance',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch for this cash balance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_balances', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this shift occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_shifts', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch associated with this manual entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='branch.branch'),
        ),
    ]
