# Generated by Django 5.1.2 on 2026-02-02 09:31

import apps.base.managers
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_add_district_rename_state_to_province'),
        ('cashandbank', '0023_alter_accountledger_branch_alter_bankaccount_branch_and_more'),
        ('tenant', '0007_alter_tenant_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cheque',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='cheque',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch associated with this cheque', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cheque',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this cheque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['tenant'], name='cheque_tenant__c6337f_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['branch'], name='cheque_branch__9f4ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['due_date'], name='cheque_due_dat_be95e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['is_active'], name='cheque_is_acti_83baaa_idx'),
        ),
        migrations.AlterModelTable(
            name='cheque',
            table='cheque',
        ),
    ]
