# Generated by Django 6.0 on 2026-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashandbank", "0024_alter_cheque_managers_cheque_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheque",
            name="cheque_type",
            field=models.CharField(
                choices=[("issued", "Issued"), ("received", "Received")], max_length=10
            ),
        ),
    ]
