# Generated by Django 6.0 on 2025-12-08 06:13

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_name', models.CharField(max_length=255, unique=True)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_user', models.PositiveIntegerField(default=1)),
                ('no_of_branch', models.PositiveIntegerField(default=1)),
                ('support_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'Chat'), ('ticket', 'Ticket')], default='email', max_length=50)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plan',
                'ordering': ['plan_price'],
            },
        ),
    ]
