# Generated by Django 5.1.2 on 2025-12-18 07:02

import apps.base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('objects', apps.base.managers.TenantManager()),
            ],
        ),
    ]
