# Generated by Django 6.0 on 2025-12-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='support_type',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='no_of_product',
            field=models.CharField(default=6, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='no_of_branch',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='no_of_user',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
