# Generated by Django 6.0 on 2025-12-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_subscriptionplan_support_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='renew_date',
        ),
    ]
