# Generated by Django 5.2.7 on 2025-12-22 06:47

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscription_renew_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Subscriber Email',
                'verbose_name_plural': 'Subscriber Emails',
                'db_table': 'subscription_subscriber_email',
                'ordering': ['-created'],
            },
        ),
    ]
