# Generated by Django 5.1.2 on 2026-01-19 09:11

import apps.subscription.models.subscription
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscriberemail'),
        ('tenant', '0007_alter_tenant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberemail',
            name='email',
            field=models.EmailField(help_text='Valid email address for subscriber', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='finish_date',
            field=models.DateField(help_text='Date when subscription ends (cannot be in the past)', validators=[apps.subscription.models.subscription.no_past_date]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_date',
            field=models.DateField(help_text='Date when subscription starts (cannot be in the past)', validators=[apps.subscription.models.subscription.no_past_date]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(help_text='Subscription plan associated', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant subscribed to the plan', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='no_of_branch',
            field=models.CharField(default='1', help_text='Number of branches allowed (number or "unlimited")', max_length=50, validators=[django.core.validators.RegexValidator(message='Must be a positive number or "unlimited"', regex='^\\d+$|^unlimited$')]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='no_of_product',
            field=models.CharField(help_text='Number of products allowed (number or "unlimited")', max_length=50, validators=[django.core.validators.RegexValidator(message='Must be a positive number or "unlimited"', regex='^\\d+$|^unlimited$')]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='no_of_user',
            field=models.CharField(default='1', help_text='Number of users allowed (number or "unlimited")', max_length=50, validators=[django.core.validators.RegexValidator(message='Must be a positive number or "unlimited"', regex='^\\d+$|^unlimited$')]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(help_text='Unique name for the subscription plan', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, help_text='Price must be greater than 0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
